import RegisterPage from "../register_page/register_page";
import { expect, describe, test } from "@jest/globals";

describe("test: render RegisterPage function return HTMLElement", () => {
  const registerPage: RegisterPage = new RegisterPage();
  const result: HTMLElement = document.createElement("div");
  result.className = "register";
  result.innerHTML =
    '<h2 class="register__caption"></h2><section class="register__section-basic"><input class="register__input-reg-email" placeholder="email"><span class="register__email-error"></span><input class="register__input-reg-password" placeholder="password"><span class="register__password-error"></span><input class="register__input-reg-first-name" placeholder="first name"><span class="register__name-error"></span><input class="register__input-reg-last-name" placeholder="last name"><span class="register__surname-error"></span><input class="register__input-reg-date" type="date"><span class="register__date-error"></span></section><section class="register__section-address"><div class="register__section-basic-billing"><h5 class="register__tittle-billing-address"></h5><select class="register__input-billing-country"><option>Belarus</option><option>Italy</option></select><input class="register__input-billing-city" placeholder="city"><span class="register__billing-city-error"></span><input class="register__input-billing-postcode" placeholder="postcode"><span class="register__billing-code-error"></span><input class="register__input-billing-street" placeholder="street"><span class="register__billing-street-error"></span><div class="register__billing-wrapper-checkbox"><input class="register__checkbox-billing_default" id="address-billing-default" type="checkbox"><label class="register__label-checkbox" for="address-billing-default">default</label></div><div class="register__united-wrapper-checkbox"><input class="register__checkbox-united" id="address-united" type="checkbox"><label class="register__label-united" for="address-united">use this address for both billing and shipping</label></div></div><div class="register__section-basic-shipping"><h5 class="register__tittle-shipping-address"></h5><select class="register__input-shipping-country"><option>Belarus</option><option>Italy</option></select><input class="register__input-shipping-city" placeholder="city"><span class="register__shipping-city-error"></span><input class="register__input-shipping-postcode" placeholder="postcode"><span class="register__shipping-code-error"></span><input class="register__input-shipping-street" placeholder="street"><span class="register__shipping-street-error"></span><div class="register__shipping-wrapper-checkbox"><input class="register__checkbox-shipping_default" id="address-shipping-default" type="checkbox"><label class="register__label-checkbox" for="address-shipping-default">default</label></div></div></section><button class="register__btn-register">Registration</button><span class="register__error"></span><span class="register__choice"></span><a href="#login"><button class="register__btn-login">Go to login</button></a>';
  test("Test1", () => {
    expect(result).toStrictEqual(registerPage.render());
  });
});
